vich_uploader:
    db_driver: orm
    mappings:
        upload_image:
            uri_prefix: /images/upload
            upload_destination: '%kernel.project_dir%/public/images/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
